//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSIGNDVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoSIGNDVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ashkaskanjkbnsjas&quot;.
        /// </summary>
        internal static string BodyEmailAprobarNomina {
            get {
                return ResourceManager.GetString("BodyEmailAprobarNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado una nueva solicitud de nomina.
        /// </summary>
        internal static string DescripcionNuevaNomina {
            get {
                return ResourceManager.GetString("DescripcionNuevaNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su pago se ha hecho efectivo.
        /// </summary>
        internal static string DescripcionNuevoPago {
            get {
                return ResourceManager.GetString("DescripcionNuevoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dvc.serviciocomunitario@dividendovoluntario.org.
        /// </summary>
        internal static string EmailDVC {
            get {
                return ResourceManager.GetString("EmailDVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comunitario2017.
        /// </summary>
        internal static string PasswordDVC {
            get {
                return ResourceManager.GetString("PasswordDVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string Puerto {
            get {
                return ResourceManager.GetString("Puerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMINA.
        /// </summary>
        internal static string TipoNotificacionNomina {
            get {
                return ResourceManager.GetString("TipoNotificacionNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGO.
        /// </summary>
        internal static string TipoNotificacionPago {
            get {
                return ResourceManager.GetString("TipoNotificacionPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Nomina.
        /// </summary>
        internal static string TituloNuevaNomina {
            get {
                return ResourceManager.GetString("TituloNuevaNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Pago.
        /// </summary>
        internal static string TituloNuevoPago {
            get {
                return ResourceManager.GetString("TituloNuevoPago", resourceCulture);
            }
        }
    }
}
